# Named navigation goals (map frame).
diadromos:
  x: -1.978
  y: -4.786
  yaw: 0.0
dock:
  x: -0.995
  y: -1.706
  yaw: -2.766
domatio tou max:
  x: -6.3
  y: -3.523
  yaw: 0.0
domatio tou mbamba:
  x: -4.167
  y: -1.951
  yaw: 0.0
kouzina:
  x: -4.391
  y: -6.245
  yaw: 0.0
saloni:
  x: -0.631
  y: -1.277
  yaw: 0.0
toualeta:
  x: -1.726
  y: -6.385
  yaw: 0.0
